Update Programming_Guide.md
 [ADVSWallAdLoader show]後、以下の例外が発生する問題が起きないように記述を修正しました。

android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?